#!/bin/bash
# Zerodha Kite MCP Server Setup
# Usage: ./setup-zerodha-mcp.sh

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$SCRIPT_DIR"

echo "======================================"
echo "Zerodha Kite MCP Server Setup"
echo "======================================"
echo ""

# Check if kiteconnect is installed
if ! python3 -c "from kiteconnect import KiteConnect" 2>/dev/null; then
    echo "Installing kiteconnect..."
    .venv/bin/pip install kiteconnect
    echo ""
fi

echo "✅ Dependencies installed"
echo ""
echo "======================================"
echo "CONFIGURATION REQUIRED"
echo "======================================"
echo ""
echo "To use Zerodha Kite MCP server, you need:"
echo ""
echo "1. Zerodha Kite Connect API Key"
echo "   - Get from: https://kite.trade"
echo "   - Cost: ₹2000 + GST (one-time)"
echo ""
echo "2. Access Token (generated via login flow)"
echo "   - Login URL: https://kite.zerodha.com/connect/login?api_key=YOUR_API_KEY"
echo "   - After login, you get request_token"
echo "   - Exchange request_token for access_token"
echo ""
echo "3. Set environment variables:"
echo ""
echo "   export ZERODHA_API_KEY=your_api_key"
echo "   export ZERODHA_ACCESS_TOKEN=your_access_token"
echo ""
echo "Or add to ~/.bashrc for persistence:"
echo ""
echo "   echo 'export ZERODHA_API_KEY=your_api_key' >> ~/.bashrc"
echo "   echo 'export ZERODHA_ACCESS_TOKEN=your_access_token' >> ~/.bashrc"
echo "   source ~/.bashrc"
echo ""
echo "======================================"
echo "NIFTY 50 / BANKNIFTY Instrument Tokens"
echo "======================================"
echo ""
echo "Common instrument tokens for Nifty/Banknifty:"
echo ""
echo "  NIFTY 50 (Cash):"
echo "    - Symbol: NSE:NIFTY 50"
echo "    - Token: Not directly tradable (use futures)"
echo ""
echo "  NIFTY Futures (Current Month):"
echo "    - Symbol: NFO:NIFTY26MAYFUT (May 2026)"
echo "    - Token: Check via kite_get_instruments"
echo ""
echo "  BANKNIFTY Futures (Current Month):"
echo "    - Symbol: NFO:BANKNIFTY26MAYFUT (May 2026)"
echo "    - Token: Check via kite_get_instruments"
echo ""
echo "  NIFTY Options:"
echo "    - Symbol: NFO:NIFTY26MAY46000CE (46000 CE May 2026)"
echo "    - Format: NFO:NIFTY<DD><MON><STRIKE><CE/PE>"
echo ""
echo "======================================"
echo "Add to Hermes Config"
echo "======================================"
echo ""
echo "Add to ~/.hermes/config.yaml:"
echo ""
echo "mcp_servers:"
echo "  zerodha-kite:"
echo "    command: \"bash\""
echo "    args:"
echo "      - \"-c\""
echo "      - \"source ~/.bashrc && exec python /home/palbot/Projects/log-fib-scalper/mcp/zerodha_kite_mcp.py\""
echo "    timeout: 60"
echo "    env:"
echo "      ZERODHA_API_KEY: \"your_api_key\""
echo "      ZERODHA_ACCESS_TOKEN: \"your_access_token\""
echo ""
echo "Then restart Hermes:"
echo "  hermes gateway restart"
echo ""
echo "======================================"
echo "Test It"
echo "======================================"
echo ""
echo "Once configured, ask Hermes:"
echo ""
echo "  Get Nifty 50 real-time quote"
echo "  Get LTP for NIFTY and BANKNIFTY"
echo "  Search for Nifty futures instruments"
echo "  Get historical data for Nifty 50"
echo ""
echo "======================================"
