#!/usr/bin/env python3
"""
LOG-FIB GEOMETRIC SCALPER - PRODUCTION READY
Optimal Configuration for XAGUSD (Silver)

Generated by Hermes Quant Squad
Optimization Date: 2026
"""

import csv
import math
import os
from datetime import datetime

# ═══════════════════════════════════════════════════════════════
# OPTIMAL PARAMETERS (from parameter_sweep_v2.py)
# ═══════════════════════════════════════════════════════════════
LOOKBACK = 12          # bars
MULTIPLIER = 0.382     # Log-Fib multiplier
ENTRY_RATIO = 0.5      # 50% Fibonacci retracement
TP_RATIO = 0.786       # Take profit at 0.786 extension
SL_RATIO = 1.0         # Stop loss at 1.0 extension
# ═══════════════════════════════════════════════════════════════

def load_data(csv_path):
    """Load OHLCV data from CSV"""
    bars = []
    with open(csv_path, mode='r', encoding='utf-8') as f:
        reader = csv.DictReader(f)
        for row in reader:
            bars.append({
                'time': row['time'],
                'open': float(row['open']),
                'high': float(row['high']),
                'low': float(row['low']),
                'close': float(row['close']),
                'volume': int(row['Volume'])
            })
    return bars

def detect_swings(bars, lookback):
    """Detect swing highs and swing lows"""
    swing_highs = []
    swing_lows = []
    
    for i in range(lookback, len(bars) - lookback):
        # Swing High
        current_high = bars[i]['high']
        is_swing_high = True
        for j in range(i - lookback, i + lookback + 1):
            if j != i and bars[j]['high'] >= current_high:
                is_swing_high = False
                break
        if is_swing_high:
            swing_highs.append({
                'idx': i,
                'time': bars[i]['time'],
                'high': current_high,
                'low': bars[i]['low']  # Anchored low
            })
        
        # Swing Low
        current_low = bars[i]['low']
        is_swing_low = True
        for j in range(i - lookback, i + lookback + 1):
            if j != i and bars[j]['low'] <= current_low:
                is_swing_low = False
                break
        if is_swing_low:
            swing_lows.append({
                'idx': i,
                'time': bars[i]['time'],
                'low': current_low,
                'high': bars[i]['high']  # Anchored high
            })
    
    return swing_highs, swing_lows

def calculate_projection(swing_point, is_high=True):
    """Calculate Log-Fib projection levels"""
    if is_high:
        price = swing_point['high']
        anchor = swing_point['low']
        log_val = math.log10(price)
        range_diff = abs(price - anchor)
        effective_range = log_val * range_diff * MULTIPLIER * 4.0
        
        entry = price - (ENTRY_RATIO * effective_range)
        tp = price - (TP_RATIO * effective_range)
        sl = price + (SL_RATIO * effective_range)
        
        return {
            'type': 'SHORT',
            'swing_time': swing_point['time'],
            'swing_price': price,
            'anchor_price': anchor,
            'entry': entry,
            'tp': tp,
            'sl': sl,
            'effective_range': effective_range
        }
    else:
        price = swing_point['low']
        anchor = swing_point['high']
        log_val = math.log10(price)
        range_diff = abs(price - anchor)
        effective_range = log_val * range_diff * MULTIPLIER * 4.0
        
        entry = price + (ENTRY_RATIO * effective_range)
        tp = price + (TP_RATIO * effective_range)
        sl = price - (SL_RATIO * effective_range)
        
        return {
            'type': 'LONG',
            'swing_time': swing_point['time'],
            'swing_price': price,
            'anchor_price': anchor,
            'entry': entry,
            'tp': tp,
            'sl': sl,
            'effective_range': effective_range
        }

def scan_for_signals(bars, swing_highs, swing_lows, lookback=50):
    """Scan recent swings for active trading signals"""
    signals = []
    
    # Check last 3 swing highs for SHORT setups
    for swing in swing_highs[-3:]:
        proj = calculate_projection(swing, is_high=True)
        signals.append(proj)
    
    # Check last 3 swing lows for LONG setups
    for swing in swing_lows[-3:]:
        proj = calculate_projection(swing, is_high=False)
        signals.append(proj)
    
    return signals

def run_scalper(csv_path):
    """Main scalper engine"""
    print("="*80)
    print("LOG-FIB GEOMETRIC SCALPER - PRODUCTION READY")
    print("="*80)
    print(f"Data: {csv_path}")
    print(f"Configuration:")
    print(f"  Lookback:      {LOOKBACK} bars")
    print(f"  Multiplier:    {MULTIPLIER}")
    print(f"  Entry:         {ENTRY_RATIO} (Fib retracement)")
    print(f"  Take Profit:   {TP_RATIO} (Extension)")
    print(f"  Stop Loss:     {SL_RATIO} (Extension)")
    print("="*80)
    
    bars = load_data(csv_path)
    print(f"Loaded {len(bars)} bars")
    print(f"Latest bar time: {bars[-1]['time']}")
    print()
    
    # Detect swings
    swing_highs, swing_lows = detect_swings(bars, LOOKBACK)
    print(f"Swing Highs detected: {len(swing_highs)}")
    print(f"Swing Lows detected: {len(swing_lows)}")
    print()
    
    # Generate signals
    signals = scan_for_signals(bars, swing_highs, swing_lows)
    
    print("╔══════════════════════════════════════════════════════════════════════╗")
    print("║  ACTIVE TRADING SIGNALS (Latest Swings)                              ║")
    print("╚══════════════════════════════════════════════════════════════════════╝")
    print()
    
    for i, sig in enumerate(signals, 1):
        direction = "SHORT ↓" if sig['type'] == 'SHORT' else "LONG ↑"
        print(f"Signal #{i}: {direction}")
        print(f"  Swing Time:    {sig['swing_time']}")
        print(f"  Swing Price:   {sig['swing_price']:.5f}")
        print(f"  Anchor Price:  {sig['anchor_price']:.5f}")
        print(f"  Entry Zone:    {sig['entry']:.5f}")
        print(f"  Take Profit:   {sig['tp']:.5f}")
        print(f"  Stop Loss:     {sig['sl']:.5f}")
        print(f"  Eff. Range:    {sig['effective_range']:.5f}")
        print()
    
    print("="*80)
    print("SCALPER READY - Monitor price action for entry at specified levels")
    print("="*80)
    
    return signals

if __name__ == '__main__':
    data_file = "/Users/kpal/projects/hermese/data/OANDA_XAGUSD1.csv"
    run_scalper(data_file)
